
service: middleware-ts
variablesResolutionMode: 20210326
frameworkVersion: '3'
package:
  individually: true
provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.handler
    events:
    - sqs:
        arn:
          Fn::Join:
            - ':'
            - - arn
              - aws
              - sqs
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - MyQueue
        batchSize: 1

plugins:
  - serverless-plugin-typescript